sudo: false
cache: bundler
language: ruby
bundler_args: --without local_development
script: bundle exec rake
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - jruby-19mode
  - rbx-2
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-2
notifications:
  recipients:
    - timo.roessner@googlemail.com
    - matijs@matijs.net
    - emil.rehnberg@gmail.com
  irc: "irc.freenode.org#reek"
